/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import conn.Conection;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rolando Andre
 */
public class Frm10 extends javax.swing.JFrame implements Printable{

    /**
     * Creates new form Frm10
     */
    DefaultTableModel  modelo1= new DefaultTableModel();
    private boolean band;
    private String nombre_material_principal;
    
    public Frm10() {
        initComponents();
        tabla1.setModel(modelo1);
        llenar_combo();
    }
    
    private void llenar_combo(){
        cbo_material.removeAllItems();
        Connection cn=null;
        Statement st=null;
        try{
            cn=Conection.getConnection();
            st=cn.createStatement();
            
            ResultSet rs=st.executeQuery("select NOMBRE from dbo.MATERIAL");
            
            cbo_material.addItem("..........................");
            while(rs.next()){
                cbo_material.addItem(rs.getString(1));
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbo_material = new javax.swing.JComboBox();
        btn_ingresar = new javax.swing.JButton();
        btn_mostrar = new javax.swing.JButton();
        spin1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panel2 = new javax.swing.JPanel();
        txt_codigoEstilo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(464, 485));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(464, 485));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ASIGNACIÓN DE MATERIALES");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 30, 250, 22);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Material:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 140, 60, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 110, 60, 20);

        cbo_material.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".........................." }));
        jPanel1.add(cbo_material);
        cbo_material.setBounds(90, 140, 100, 25);

        btn_ingresar.setForeground(new java.awt.Color(102, 102, 102));
        btn_ingresar.setText("Ingresar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ingresar);
        btn_ingresar.setBounds(230, 90, 90, 30);

        btn_mostrar.setForeground(new java.awt.Color(102, 102, 102));
        btn_mostrar.setText("Mostrar");
        btn_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_mostrar);
        btn_mostrar.setBounds(230, 130, 90, 30);

        spin1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        jPanel1.add(spin1);
        spin1.setBounds(90, 110, 40, 25);

        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(330, 130, 90, 30);

        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(330, 90, 90, 30);

        panel2.setBackground(new java.awt.Color(255, 255, 255));
        panel2.setLayout(null);
        panel2.add(txt_codigoEstilo);
        txt_codigoEstilo.setBounds(110, 10, 100, 25);

        tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla1);

        panel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 390, 140);

        jLabel2.setText("Codigo de Estilo:");
        panel2.add(jLabel2);
        jLabel2.setBounds(10, 10, 100, 20);

        jPanel1.add(panel2);
        panel2.setBounds(20, 170, 410, 200);

        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setText("Imprimir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(320, 380, 110, 40);

        jMenu1.setText("Opción");

        jMenuItem1.setText("Regresar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        Connection cn=null;
        Statement st=null;
        try{
            
            String codigo_estilo=txt_codigoEstilo.getText().toUpperCase().trim();
            if(!codigo_estilo.equalsIgnoreCase("")){
                if(Validacion.existe_codigo_estilo(codigo_estilo)){
                    String material=cbo_material.getSelectedItem().toString();
                    if(!material.equalsIgnoreCase("..........................")){
                        int cantidad=(int)spin1.getValue();
                        cn=Conection.getConnection();
                        st=cn.createStatement();
                        
                        boolean band=false;
                        int codigo_material=0,codigo_ficha=0;
                        
                        ResultSet rs=st.executeQuery("select COD_MATERIAL from dbo.MATERIAL where NOMBRE='"+material+"'");
                        
                        if(rs.next()){
                            codigo_material=rs.getInt(1);
                        }
                        
                        
                        ResultSet rs2=st.executeQuery("select COD_FICHA from dbo.FICHA_TECNICA where COD_ESTILO='C001'");
                      
                        if(rs2.next()){
                            codigo_ficha=rs2.getInt(1);
                        }
                        
                        if(codigo_material>0&&codigo_ficha>0){
                            
                            ResultSet rs3=st.executeQuery("select * from dbo.FICHA_MATERIAL where COD_FICHA='"+Integer.toString(codigo_ficha)+"' and COD_MATERIAL='"+Integer.toString(codigo_material)+"'");
                            
                            if(rs3.next()){
                                band=true;
                            }
                            
                            if(!band){
                                int input=JOptionPane.showConfirmDialog(null, "Estás seguro?","Escoger una opción",2,3);
                                if(input==0){
                                    st.executeUpdate("insert into dbo.FICHA_MATERIAL VALUES('"+Integer.toString(codigo_ficha)+"','"+Integer.toString(codigo_material)+"','"+Integer.toString(cantidad)+"')");
                                    JOptionPane.showMessageDialog(null,"Se ingresó correctamente!!");
                                    listar();
                                }
                            }else{
                                JOptionPane.showMessageDialog(null,"El material ya ha sido asignado anteriormente!!","Mensaje",3);
                            }
                            
                        }else{
                            JOptionPane.showMessageDialog(null,"No se pudo ingresar!!");
                        }
                    }else{
                        JOptionPane.showMessageDialog(null,"Complete todos los campos!!","Mensaje",3);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Ese codigo de estilo no existe!!","Mensaje",2);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Complete todos los campos!!","Mensaje",3);
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarActionPerformed
        
        listar();
        
    }//GEN-LAST:event_btn_mostrarActionPerformed

    private void listar(){
        Connection cn=null;
        Statement st=null;
        try{
            this.band=false;
            
            String codigo_estilo=txt_codigoEstilo.getText().toUpperCase().trim();
            
            if(!codigo_estilo.equalsIgnoreCase("")){
                if(Validacion.existe_codigo_estilo(codigo_estilo)){
                    
                    cn=Conection.getConnection();
                    st=cn.createStatement();
                    
                    ResultSet rs=st.executeQuery("select M.NOMBRE as MATERIAL,FT.CANTIDAD as CANTIDAD from FICHA_MATERIAL FT,MATERIAL M where FT.COD_MATERIAL=M.COD_MATERIAL");
                    
                    modelo1.setColumnCount(0);
                    modelo1.setRowCount(0);
                    
                    ResultSetMetaData md=rs.getMetaData();
                    int cantidad_columnas=md.getColumnCount();
                    for(int i=1;i<=cantidad_columnas;i++){
                        modelo1.addColumn(md.getColumnName(i));
                    }
                    
                    while(rs.next()){
                        Object[] fila=new Object[cantidad_columnas];
                        for(int i=0;i<cantidad_columnas;i++){
                            fila[i]=rs.getObject(i+1);
                        }
                        modelo1.addRow(fila);
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Ese codigo de estilo no existe!!","Mensaje",2);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Ingrese un codigo de estilo para visualizar sus materiales!!","Mensaje",3);
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection cn=null;
        Statement st=null;
        try{
            cn=Conection.getConnection();
            st=cn.createStatement();
            if(band){
                String codigo_estilo=txt_codigoEstilo.getText().toUpperCase().trim();
                if(!codigo_estilo.equalsIgnoreCase("")){
                    if(Validacion.existe_codigo_estilo(codigo_estilo)){
                            int cantidad=(int)spin1.getValue();
                            
                                int input=JOptionPane.showConfirmDialog(null, "Estás seguro?","Escoger una opción",2,3);
                                if(input==0){
                                    st.executeUpdate("update dbo.FICHA_MATERIAL set CANTIDAD='"+cantidad+"' where COD_FICHA=(select FT.COD_FICHA from dbo.FICHA_TECNICA FT where FT.COD_ESTILO='"+codigo_estilo+"') and COD_MATERIAL=(select M.COD_MATERIAL from dbo.MATERIAL M where M.NOMBRE='"+this.nombre_material_principal+"')");
                            
                                    this.band=false;

                                    JOptionPane.showMessageDialog(null,"La cantidad ha sido modificada correctamente!!");
                                    listar();
                                }
                        
                    }else{
                        JOptionPane.showMessageDialog(null, "Ese código de estilo no existe!!","Mensaje",2);
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Ingrese un código de estilo para modificar material registrado!!","Mensaje",3);
                }
            }else{
                JOptionPane.showMessageDialog(null,"seleccione una fila de la tabla!!");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla1MouseClicked
        int fila_seleccionada=tabla1.getSelectedRow();
        
        if(fila_seleccionada>=0){
            cbo_material.setSelectedItem(tabla1.getValueAt(fila_seleccionada, 0).toString());
            spin1.setValue(Integer.parseInt(tabla1.getValueAt(fila_seleccionada, 1).toString()));
            this.nombre_material_principal=tabla1.getValueAt(fila_seleccionada, 0).toString();
            this.band=true;
        }
    }//GEN-LAST:event_tabla1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Connection cn=null;
        Statement st=null;
        try{
            cn=Conection.getConnection();
            st=cn.createStatement();
            if(band){
                String codigo_estilo=txt_codigoEstilo.getText().toUpperCase().trim();
                if(!codigo_estilo.equalsIgnoreCase("")){
                    if(Validacion.existe_codigo_estilo(codigo_estilo)){
                        String material=cbo_material.getSelectedItem().toString();
                        if(!material.equalsIgnoreCase("..........................")){
                            int cantidad=(int)spin1.getValue();
                            
                            boolean existe_material=false;
                            
                            ResultSet rs=st.executeQuery("select * from dbo.FICHA_MATERIAL FM where FM.COD_MATERIAL=(select M.COD_MATERIAL from dbo.MATERIAL M where M.NOMBRE='"+material+"') and FM.COD_FICHA=(select FT.COD_FICHA from dbo.FICHA_TECNICA FT where FT.COD_ESTILO='"+codigo_estilo+"')");
                           
                            if(rs.next()){
                                existe_material=true;
                            }
                            
                            if(existe_material){
                                int input=JOptionPane.showConfirmDialog(null, "Estás seguro?","Escoger una opción",2,3);
                                if(input==0){
                                    st.executeUpdate("delete from dbo.FICHA_MATERIAL where COD_FICHA=(select FT.COD_FICHA from dbo.FICHA_TECNICA FT where FT.COD_ESTILO='"+codigo_estilo+"') and COD_MATERIAL=(select M.COD_MATERIAL from dbo.MATERIAL M where M.NOMBRE='"+material+"')");
                            
                                    this.band=false;

                                    JOptionPane.showMessageDialog(null,"Se eliminó correctamente!!");
                                    listar();
                                }
                            }else{
                                JOptionPane.showMessageDialog(null,"No se pudo eliminar. El material no figura en la ficha técnica!!","Mensaje",3);
                            }
                        }else{
                            JOptionPane.showMessageDialog(null,"Complete todos los campos!!","Mensaje",3);
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "Ese código de estilo no existe!!","Mensaje",2);
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Ingrese un código de estilo para eliminar un material registrado!!","Mensaje",3);
                }
            }else{
                JOptionPane.showMessageDialog(null,"seleccione una fila de la tabla!!");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Frm5 obj=new Frm5();
        obj.setVisible(true);
        obj.setResizable(false);
        obj.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            PrinterJob gap= PrinterJob.getPrinterJob();
            gap.setPrintable(this);
            boolean top=gap.printDialog();
            if(top){
                gap.print();
            }
            
           
        }catch(PrinterException ex){
            JOptionPane.showMessageDialog(null, "Error de programa","Error\n"+ex.getMessage(),JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_mostrar;
    private javax.swing.JComboBox cbo_material;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel2;
    private javax.swing.JSpinner spin1;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField txt_codigoEstilo;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        if(pageIndex>0){
            return NO_SUCH_PAGE;
        }
        Graphics2D hub=(Graphics2D) graphics;
        hub.translate(pageFormat.getImageableX()+20,pageFormat.getImageableY()+20);
        hub.scale(1.0, 1.0);
        
        panel2.printAll(graphics);
        return PAGE_EXISTS; 
    }
}
