/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import conn.Conection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rolando Andre
 */
public class Frm10 extends javax.swing.JFrame {

    /**
     * Creates new form Frm10
     */
    DefaultTableModel  modelo1= new DefaultTableModel();
    
    public Frm10() {
        initComponents();
        tabla1.setModel(modelo1);
        llenar_combo();
    }
    
    private void llenar_combo(){
        cbo_material.removeAllItems();
        Connection cn=null;
        Statement st=null;
        try{
            cn=Conection.getConnection();
            st=cn.createStatement();
            
            ResultSet rs=st.executeQuery("select NOMBRE from dbo.MATERIAL");
            
            cbo_material.addItem("..........................");
            while(rs.next()){
                cbo_material.addItem(rs.getString(1));
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_codigoEstilo = new javax.swing.JTextField();
        cbo_material = new javax.swing.JComboBox();
        btn_ingresar = new javax.swing.JButton();
        btn_mostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        spin1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Ingresar Materiales");

        jLabel2.setText("Codigo de Estilo:");

        jLabel3.setText("Material:");

        jLabel4.setText("Cantidad:");

        cbo_material.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ".........................." }));

        btn_ingresar.setText("Ingresar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });

        btn_mostrar.setText("Mostrar");
        btn_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(tabla1);

        spin1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(txt_codigoEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel3)
                .addGap(68, 68, 68)
                .addComponent(cbo_material, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel4)
                .addGap(63, 63, 63)
                .addComponent(spin1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(btn_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_codigoEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cbo_material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(spin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        Connection cn=null;
        Statement st=null;
        try{
            
            String codigo_estilo=txt_codigoEstilo.getText().toUpperCase().trim();
            if(!codigo_estilo.equalsIgnoreCase("")){
                if(Validacion.existe_codigo_estilo(codigo_estilo)){
                    String material=cbo_material.getSelectedItem().toString();
                    if(!material.equalsIgnoreCase("..........................")){
                        int cantidad=(int)spin1.getValue();
                        cn=Conection.getConnection();
                        st=cn.createStatement();
                        
                        boolean band=false;
                        int codigo_material=0,codigo_ficha=0;
                        
                        ResultSet rs=st.executeQuery("select COD_MATERIAL from dbo.MATERIAL where NOMBRE='"+material+"'");
                        
                        if(rs.next()){
                            codigo_material=rs.getInt(1);
                        }
                        
                        
                        ResultSet rs2=st.executeQuery("select COD_FICHA from dbo.FICHA_TECNICA where COD_ESTILO='C001'");
                      
                        if(rs2.next()){
                            codigo_ficha=rs2.getInt(1);
                        }
                        
                        if(codigo_material>0&&codigo_ficha>0){
                            
                            ResultSet rs3=st.executeQuery("select * from dbo.FICHA_MATERIAL where COD_FICHA='"+Integer.toString(codigo_ficha)+"' and COD_MATERIAL='"+Integer.toString(codigo_material)+"'");
                            
                            if(rs3.next()){
                                band=true;
                            }
                            
                            if(!band){
                                int input=JOptionPane.showConfirmDialog(null, "Estás seguro?","Escoger una opción",2,3);
                                if(input==0){
                                    st.executeUpdate("insert into dbo.FICHA_MATERIAL VALUES('"+Integer.toString(codigo_ficha)+"','"+Integer.toString(codigo_material)+"','"+Integer.toString(cantidad)+"')");
                                    JOptionPane.showMessageDialog(null,"Se ingresó correctamente!!");
                                }
                            }else{
                                JOptionPane.showMessageDialog(null,"El material ya ha sido asignado anteriormente!!","Mensaje",3);
                            }
                            
                        }else{
                            JOptionPane.showMessageDialog(null,"No se pudo ingresar!!");
                        }
                    }else{
                        JOptionPane.showMessageDialog(null,"Complete todos los campos!!","Mensaje",3);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Ese codigo de estilo no existe!!","Mensaje",2);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Complete todos los campos!!","Mensaje",3);
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarActionPerformed
        
        Connection cn=null;
        Statement st=null;
        try{
            
            String codigo_estilo=txt_codigoEstilo.getText().toUpperCase().trim();
            
            if(!codigo_estilo.equalsIgnoreCase("")){
                if(Validacion.existe_codigo_estilo(codigo_estilo)){
                    
                    cn=Conection.getConnection();
                    st=cn.createStatement();
                    
                    ResultSet rs=st.executeQuery("select M.NOMBRE as MATERIAL,FT.CANTIDAD as CANTIDAD from FICHA_MATERIAL FT,MATERIAL M where FT.COD_MATERIAL=M.COD_MATERIAL");
                    
                    modelo1.setColumnCount(0);
                    modelo1.setRowCount(0);
                    
                    ResultSetMetaData md=rs.getMetaData();
                    int cantidad_columnas=md.getColumnCount();
                    for(int i=1;i<=cantidad_columnas;i++){
                        modelo1.addColumn(md.getColumnName(i));
                    }
                    
                    while(rs.next()){
                        Object[] fila=new Object[cantidad_columnas];
                        for(int i=0;i<cantidad_columnas;i++){
                            fila[i]=rs.getObject(i+1);
                        }
                        modelo1.addRow(fila);
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Ese codigo de estilo no existe!!","Mensaje",2);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Ingrese un codigo de estilo para visualizar sus materiales!!","Mensaje",3);
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        
    }//GEN-LAST:event_btn_mostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_mostrar;
    private javax.swing.JComboBox cbo_material;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spin1;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField txt_codigoEstilo;
    // End of variables declaration//GEN-END:variables
}
