/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Rolando Andre
 */
public class Frm3 extends javax.swing.JFrame {

    /**
     * Creates new form Frm3
     */
    public Frm3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_codigoEstilo = new javax.swing.JTextField();
        btn_grabar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_codigo = new javax.swing.JTextField();
        txt_prendasBienElaboradas = new javax.swing.JTextField();
        txt_prendasMalElaboradas = new javax.swing.JTextField();
        txt_horasTrabajadas = new javax.swing.JTextField();
        txt_fecha = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_mostrar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_codigoEstilo3 = new javax.swing.JTextField();
        txt_codigoEstilo2 = new javax.swing.JTextField();
        btn_mostrarProduccion = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txt_fechaInicio = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        txt_fechaFin = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ingresar avances de empleado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 20, -1, -1));

        jLabel2.setText("Código de Estilo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 73, -1, -1));
        getContentPane().add(txt_codigoEstilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 173, -1));

        btn_grabar.setText("Grabar");
        getContentPane().add(btn_grabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 93, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Criterio"));

        jLabel4.setText("Código:");

        jLabel5.setText("Fecha:");

        jLabel6.setText("Prendas bien elaboradas:");

        jLabel7.setText("Prendas mal elaboradas:");

        jLabel8.setText("Horas trabajadas:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 122, 180, 177));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, -1));
        jPanel2.add(txt_prendasBienElaboradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 180, -1));

        txt_prendasMalElaboradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_prendasMalElaboradasActionPerformed(evt);
            }
        });
        jPanel2.add(txt_prendasMalElaboradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 180, -1));
        jPanel2.add(txt_horasTrabajadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, -1));
        jPanel2.add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 122, 230, 177));

        jLabel3.setText("Mostrar por código de estilo y fecha");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jLabel9.setText("Cóigo de estilo:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jLabel10.setText("Fecha de inicio:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        btn_mostrar.setText("Mostrar");
        getContentPane().add(btn_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 460, 100, 30));

        jLabel11.setText("Mostrar producción total por código");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        jLabel12.setText("Código de estilo:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));
        getContentPane().add(txt_codigoEstilo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 100, -1));
        getContentPane().add(txt_codigoEstilo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 100, -1));

        btn_mostrarProduccion.setText("Mostrar Producción");
        getContentPane().add(btn_mostrarProduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 150, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 10, 120));
        getContentPane().add(txt_fechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 100, -1));

        jLabel13.setText("Fecha de fin:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 434, -1, -1));
        getContentPane().add(txt_fechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 428, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_prendasMalElaboradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_prendasMalElaboradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_prendasMalElaboradasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_grabar;
    private javax.swing.JButton btn_mostrar;
    private javax.swing.JButton btn_mostrarProduccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_codigoEstilo;
    private javax.swing.JTextField txt_codigoEstilo2;
    private javax.swing.JTextField txt_codigoEstilo3;
    private com.toedter.calendar.JDateChooser txt_fecha;
    private com.toedter.calendar.JDateChooser txt_fechaFin;
    private com.toedter.calendar.JDateChooser txt_fechaInicio;
    private javax.swing.JTextField txt_horasTrabajadas;
    private javax.swing.JTextField txt_prendasBienElaboradas;
    private javax.swing.JTextField txt_prendasMalElaboradas;
    // End of variables declaration//GEN-END:variables
}
