/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.Date;
import conn.Conection;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerListModel;
import javax.swing.SpinnerModel;

/**
 *
 * @author Rolando Andre
 */
public class Frm3 extends javax.swing.JFrame {

    /**
     * Creates new form Frm3
     */
    public Frm3() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_codigoEstilo = new javax.swing.JTextField();
        btn_grabar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_dni = new javax.swing.JTextField();
        txt_fecha = new com.toedter.calendar.JDateChooser();
        spin1 = new javax.swing.JSpinner();
        spin2 = new javax.swing.JSpinner();
        spin3 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_mostrar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_codigoEstilo3 = new javax.swing.JTextField();
        txt_codigoEstilo2 = new javax.swing.JTextField();
        btn_mostrarProduccion = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txt_fechaInicio = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        txt_fechaFin = new com.toedter.calendar.JDateChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ingresar avances de empleado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 20, -1, -1));

        jLabel2.setText("Código de Estilo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 73, -1, -1));
        getContentPane().add(txt_codigoEstilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 173, -1));

        btn_grabar.setText("Grabar");
        btn_grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_grabarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_grabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 93, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Criterio"));

        jLabel4.setText("Dni_empleado:");

        jLabel5.setText("Fecha:");

        jLabel6.setText("Prendas bien elaboradas:");

        jLabel7.setText("Prendas mal elaboradas:");

        jLabel8.setText("Horas trabajadas:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 122, 180, 177));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(txt_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, -1));

        txt_fecha.setDateFormatString("dd-MM-yyyy");
        jPanel2.add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, -1));

        spin1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        jPanel2.add(spin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, -1));

        spin2.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        jPanel2.add(spin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 60, -1));

        spin3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        jPanel2.add(spin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 60, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 122, 230, 177));

        jLabel3.setText("Mostrar por código de estilo y fecha");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jLabel9.setText("Cóigo de estilo:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jLabel10.setText("Fecha de inicio:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        btn_mostrar.setText("Mostrar");
        btn_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 460, 100, 30));

        jLabel11.setText("Mostrar producción total por código");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        jLabel12.setText("Código de estilo:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));
        getContentPane().add(txt_codigoEstilo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 100, -1));
        getContentPane().add(txt_codigoEstilo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 100, -1));

        btn_mostrarProduccion.setText("Mostrar Producción");
        getContentPane().add(btn_mostrarProduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 150, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 10, 120));
        getContentPane().add(txt_fechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 100, -1));

        jLabel13.setText("Fecha de fin:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 434, -1, -1));
        getContentPane().add(txt_fechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 428, -1, -1));

        jMenu1.setText("Options");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_TAB, 0));
        jMenuItem1.setText("Volver");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_grabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_grabarActionPerformed
        Connection cn=null;
        Statement st=null;
        try{
            String codigo_estilo=txt_codigoEstilo.getText().toUpperCase().trim();
            if(!codigo_estilo.equalsIgnoreCase("")){
                if(Validacion.existe_codigo_estilo(codigo_estilo)){
                    String dni_empleado=txt_dni.getText().toUpperCase().trim();
                    if(!dni_empleado.equalsIgnoreCase("")){
                        if(Validacion.existe_dni_empleado(dni_empleado)){
                            if(!Validacion.existencia_letras(dni_empleado)){
                                String fechaString=null;
                                Date fecha=txt_fecha.getDate();
                                if(fecha!=null){
                                    SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yy");
                                    fechaString=sdf.format(fecha);
                                    String prendas_bien=spin1.getValue().toString();
                                    String prendas_mal=spin2.getValue().toString();
                                    String horas_trab=spin3.getValue().toString();

                                    cn=Conection.getConnection();
                                    st=cn.createStatement();
                                    
                                    boolean band=false;
                                    String codigo_empleado="",codigo_ficha="";
                                    
                                    ResultSet rs=st.executeQuery("select cod_emp from dbo.EMPLEADO where DNI='"+dni_empleado+"'");
                                    
                                    if(rs.next()){
                                        codigo_empleado=rs.getString(1);
                                    }
                                    
                                    ResultSet rs2=st.executeQuery("select COD_FICHA from dbo.FICHA_TECNICA where COD_ESTILO='"+codigo_estilo+"'");
                                    
                                    if(rs2.next()){
                                        codigo_ficha=rs2.getString(1);
                                    }
                                    
                                    if(Validacion.esta_asignado(codigo_empleado, codigo_ficha)){
                                        if(!Validacion.avance_registrado_hoy(codigo_empleado,new SimpleDateFormat("dd-MM-yyyy").format(fecha))){
                                            int input=JOptionPane.showConfirmDialog(null, "Estás seguro?","Escoger una opción",2,3);
                                            if(input==0){
                                                st.executeUpdate("insert into dbo.AVANCE VALUES(convert(datetime,'"+fechaString+"',5),'"+prendas_bien+"','"+prendas_mal+"','"+horas_trab+"','"+codigo_empleado+"','"+codigo_ficha+"')");
                                                JOptionPane.showMessageDialog(null,"Se ingresó correctamente!!");
                                            }
                                        }else{
                                            JOptionPane.showMessageDialog(null,"Ya se ha registrado el avance de ese empleado en esa fecha!!","Mensaje",2);
                                        }
                                    }else{
                                        JOptionPane.showMessageDialog(null,"El empleado no esta asignado a esa ficha tecnica actualmente!!","Mensaje",2);
                                    }
                                    
                                }else{
                                    JOptionPane.showMessageDialog(null,"Complete todos los campos!!","Mensaje",3);
                                }
                            }else{
                                JOptionPane.showMessageDialog(null,"El dni no debe contener letras!!","Mensaje",2);
                            }
                        }else{
                            JOptionPane.showMessageDialog(null,"Dni de empleado no existe!!","Mensaje",3);
                        }
                    }else{
                        JOptionPane.showMessageDialog(null,"Complete todos los campos!!","Mensaje",3);
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Codigo de estilo no existe!!","Mensaje",3);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Complete todos los campos!!","Mensaje",3);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btn_grabarActionPerformed

    private void btn_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarActionPerformed
        Connection cn=null;
        Statement st=null;
        try{
            String codigo_estilo=txt_codigoEstilo2.getText().toUpperCase().trim();
            if(!codigo_estilo.equalsIgnoreCase("")){
                if(Validacion.existe_codigo_estilo(codigo_estilo)){
                    String StringFecha_inicio="";
                    Date fecha_inicio=txt_fechaInicio.getDate();
                    if(fecha_inicio!=null){
                        SimpleDateFormat sdf_uno=new SimpleDateFormat("dd-MM-yyyy");
                        StringFecha_inicio=sdf_uno.format(fecha_inicio);
                        String StringFecha_fin="";
                        Date fecha_fin=txt_fechaFin.getDate();
                        if(fecha_fin!=null){
                           SimpleDateFormat sdf_dos=new SimpleDateFormat("dd-MM-yyyy");
                           StringFecha_fin=sdf_dos.format(fecha_fin);
                           
                           
                           Frm2.codigo_estilo=codigo_estilo;
                           Frm2.StringFecha_fin=StringFecha_fin;
                           Frm2.StringFecha_inicio=StringFecha_inicio;
                           
                           Frm2 obj=new Frm2();
                           obj.setVisible(true);
                           obj.setLocationRelativeTo(null);
                           obj.setResizable(false);
                           this.dispose();
                        }else{
                            JOptionPane.showMessageDialog(null,"Complete todos los campos!!","Mensaje",3);
                        }
                    }else{
                        JOptionPane.showMessageDialog(null,"Complete todos los campos!!","Mensaje",3);
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Codigo de estilo no existe!!","Mensaje",3);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Complete todos los campos!!","Mensaje",3);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btn_mostrarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Frm8 obj=new Frm8();
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        obj.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_grabar;
    private javax.swing.JButton btn_mostrar;
    private javax.swing.JButton btn_mostrarProduccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner spin1;
    private javax.swing.JSpinner spin2;
    private javax.swing.JSpinner spin3;
    private javax.swing.JTextField txt_codigoEstilo;
    private javax.swing.JTextField txt_codigoEstilo2;
    private javax.swing.JTextField txt_codigoEstilo3;
    private javax.swing.JTextField txt_dni;
    private com.toedter.calendar.JDateChooser txt_fecha;
    private com.toedter.calendar.JDateChooser txt_fechaFin;
    private com.toedter.calendar.JDateChooser txt_fechaInicio;
    // End of variables declaration//GEN-END:variables
}
