/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import conn.Conection;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Rolando Andre
 */
public class Frm4 extends javax.swing.JFrame {

    /**
     * Creates new form Frm4
     */
    public Frm4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_codigoEstilo = new javax.swing.JTextField();
        btn_buscarPorcodigoEstilo = new javax.swing.JButton();
        btn_imprimir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_estilo = new javax.swing.JTextField();
        txt_version = new javax.swing.JTextField();
        txt_division = new javax.swing.JTextField();
        txt_descripcion = new javax.swing.JTextField();
        txt_destino = new javax.swing.JTextField();
        txt_temporada = new javax.swing.JTextField();
        txt_telaPrincipal = new javax.swing.JTextField();
        txt_proceso = new javax.swing.JTextField();
        txt_arte = new javax.swing.JTextField();
        txt_etiqueta = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_codigoEstilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 41, 180, -1));

        btn_buscarPorcodigoEstilo.setText("Burcar por codigo de estilo");
        btn_buscarPorcodigoEstilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarPorcodigoEstiloActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscarPorcodigoEstilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 40, -1, -1));

        btn_imprimir.setText("Imprimir");
        getContentPane().add(btn_imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 425, 100, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Criterio"));

        jLabel1.setText("Etiqueta:");

        jLabel2.setText("Estilo:");

        jLabel3.setText("Versión:");

        jLabel4.setText("División:");

        jLabel5.setText("Descripción:");

        jLabel6.setText("Destino:");

        jLabel7.setText("Temporada:");

        jLabel8.setText("Tela Principal:");

        jLabel9.setText("Proceso:");

        jLabel10.setText("Artes:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addGap(16, 16, 16)
                .addComponent(jLabel9)
                .addGap(16, 16, 16)
                .addComponent(jLabel10)
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(9, 9, 9))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 90, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_estilo.setEditable(false);
        jPanel2.add(txt_estilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, -1));

        txt_version.setEditable(false);
        jPanel2.add(txt_version, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 200, -1));

        txt_division.setEditable(false);
        jPanel2.add(txt_division, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 200, -1));

        txt_descripcion.setEditable(false);
        jPanel2.add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 200, -1));

        txt_destino.setEditable(false);
        jPanel2.add(txt_destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, -1));

        txt_temporada.setEditable(false);
        jPanel2.add(txt_temporada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 200, -1));

        txt_telaPrincipal.setEditable(false);
        jPanel2.add(txt_telaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 200, -1));

        txt_proceso.setEditable(false);
        jPanel2.add(txt_proceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 200, -1));

        txt_arte.setEditable(false);
        jPanel2.add(txt_arte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 200, -1));

        txt_etiqueta.setEditable(false);
        jPanel2.add(txt_etiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 200, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 89, 251, 330));

        jMenu1.setText("Option");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_TAB, 0));
        jMenuItem1.setText("Volver");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarPorcodigoEstiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarPorcodigoEstiloActionPerformed
        Connection cn=null;
        Statement st=null;
        try{
            String codigo_estilo=txt_codigoEstilo.getText().toUpperCase().trim();
            if(!codigo_estilo.equalsIgnoreCase("")){
                if(Validacion.existe_codigo_estilo(codigo_estilo)){
                    cn=Conection.getConnection();
                    st=cn.createStatement();
                    
                    ResultSet rs=st.executeQuery("select COD_ESTILO,VERSION,DIVISION,DESCRIPCION,DESTINO,TEMPORADA,TELA_PRICNIPAL,PROCESO,ARTES,ETIQUETA from dbo.FICHA_TECNICA where cod_estilo='"+codigo_estilo+"'");
                    
                    while(rs.next()){
                        txt_estilo.setText(rs.getString(1));
                        txt_version.setText(rs.getString(2));
                        txt_division.setText(rs.getString(3));
                        txt_descripcion.setText(rs.getString(4));
                        txt_destino.setText(rs.getString(5));
                        txt_temporada.setText(rs.getString(6));
                        txt_telaPrincipal.setText(rs.getString(7));
                        txt_proceso.setText(rs.getString(8));
                        txt_arte.setText(rs.getString(9));
                        txt_etiqueta.setText(rs.getString(10));
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null,"Codigo de estilo no existe!!","Mensaje",3);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Completa el campo!!","Mensaje",3);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btn_buscarPorcodigoEstiloActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Frm5 obj=new Frm5();
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        obj.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscarPorcodigoEstilo;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_arte;
    private javax.swing.JTextField txt_codigoEstilo;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_destino;
    private javax.swing.JTextField txt_division;
    private javax.swing.JTextField txt_estilo;
    private javax.swing.JTextField txt_etiqueta;
    private javax.swing.JTextField txt_proceso;
    private javax.swing.JTextField txt_telaPrincipal;
    private javax.swing.JTextField txt_temporada;
    private javax.swing.JTextField txt_version;
    // End of variables declaration//GEN-END:variables
}
