/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Rolando Andre
 */
public class Frm5 extends javax.swing.JFrame {

    /**
     * Creates new form Frm5
     */
    public Frm5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_division = new javax.swing.JTextField();
        txt_estilo = new javax.swing.JTextField();
        txt_version = new javax.swing.JTextField();
        txt_destino = new javax.swing.JTextField();
        txt_temporada = new javax.swing.JTextField();
        txt_telaPrincipal = new javax.swing.JTextField();
        txt_proceso = new javax.swing.JTextField();
        txt_arte = new javax.swing.JTextField();
        txt_etiqueta = new javax.swing.JTextField();
        txt_fechaCreacion = new com.toedter.calendar.JDateChooser();
        btnGrabar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txt_descripcion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ficha Técnica");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel2.setText("Estilo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, 20));

        jLabel3.setText("Versión:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 20));

        jLabel4.setText("División:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, 20));

        jLabel5.setText("Descripción:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 159, -1, 20));

        jLabel6.setText("Destino:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 192, -1, 20));

        jLabel7.setText("Temporada:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 223, -1, 20));

        jLabel8.setText("Tela principal:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 253, -1, 20));

        jLabel9.setText("Proceso:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 283, -1, 20));

        jLabel10.setText("Artes:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 309, -1, 20));

        jLabel11.setText("Etiqueta:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 339, -1, 20));

        jLabel12.setText("Fecha de creación:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 369, -1, 20));
        getContentPane().add(txt_division, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 200, -1));

        txt_estilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_estiloActionPerformed(evt);
            }
        });
        getContentPane().add(txt_estilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 200, -1));
        getContentPane().add(txt_version, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 200, -1));
        getContentPane().add(txt_destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 192, 200, -1));
        getContentPane().add(txt_temporada, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 223, 200, -1));
        getContentPane().add(txt_telaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 253, 200, -1));

        txt_proceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_procesoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_proceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 283, 200, -1));
        getContentPane().add(txt_arte, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 309, 200, -1));
        getContentPane().add(txt_etiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 339, 200, -1));
        getContentPane().add(txt_fechaCreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 369, 200, -1));

        btnGrabar.setText("Grabar");
        getContentPane().add(btnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 402, 110, 30));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 402, 100, 30));
        getContentPane().add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 161, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_procesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_procesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_procesoActionPerformed

    private void txt_estiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_estiloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_estiloActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_arte;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_destino;
    private javax.swing.JTextField txt_division;
    private javax.swing.JTextField txt_estilo;
    private javax.swing.JTextField txt_etiqueta;
    private com.toedter.calendar.JDateChooser txt_fechaCreacion;
    private javax.swing.JTextField txt_proceso;
    private javax.swing.JTextField txt_telaPrincipal;
    private javax.swing.JTextField txt_temporada;
    private javax.swing.JTextField txt_version;
    // End of variables declaration//GEN-END:variables
}
