/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import conn.Conection;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Rolando Andre
 */
public class Frm5 extends javax.swing.JFrame {

    /**
     * Creates new form Frm5
     */
    public Frm5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_division = new javax.swing.JTextField();
        txt_estilo = new javax.swing.JTextField();
        txt_version = new javax.swing.JTextField();
        txt_destino = new javax.swing.JTextField();
        txt_temporada = new javax.swing.JTextField();
        txt_telaPrincipal = new javax.swing.JTextField();
        txt_proceso = new javax.swing.JTextField();
        txt_arte = new javax.swing.JTextField();
        txt_etiqueta = new javax.swing.JTextField();
        txt_fechaCreacion = new com.toedter.calendar.JDateChooser();
        btnGrabar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txt_descripcion = new javax.swing.JTextField();
        btn_limpiar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ficha Técnica");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel2.setText("Estilo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, 20));

        jLabel3.setText("Versión:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 20));

        jLabel4.setText("División:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, 20));

        jLabel5.setText("Descripción:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 159, -1, 20));

        jLabel6.setText("Destino:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 192, -1, 20));

        jLabel7.setText("Temporada:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 223, -1, 20));

        jLabel8.setText("Tela principal:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 253, -1, 20));

        jLabel9.setText("Proceso:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 283, -1, 20));

        jLabel10.setText("Artes:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 309, -1, 20));

        jLabel11.setText("Etiqueta:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 339, -1, 20));

        jLabel12.setText("Fecha de creación:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 369, -1, 20));
        getContentPane().add(txt_division, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 200, -1));

        txt_estilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_estiloActionPerformed(evt);
            }
        });
        getContentPane().add(txt_estilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 200, -1));
        getContentPane().add(txt_version, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 200, -1));
        getContentPane().add(txt_destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 192, 200, -1));
        getContentPane().add(txt_temporada, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 223, 200, -1));
        getContentPane().add(txt_telaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 253, 200, -1));

        txt_proceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_procesoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_proceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 283, 200, -1));
        getContentPane().add(txt_arte, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 309, 200, -1));
        getContentPane().add(txt_etiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 339, 200, -1));
        getContentPane().add(txt_fechaCreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 369, 200, -1));

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 110, 30));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 100, 30));
        getContentPane().add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 161, 200, -1));

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 100, 30));

        jMenu1.setText("Options");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_TAB, 0));
        jMenuItem1.setText("Volver");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_procesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_procesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_procesoActionPerformed

    private void txt_estiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_estiloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_estiloActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Frm4 obj=new Frm4();
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        obj.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        Connection cn=null;
        Statement st=null;
        try{
            String codigo_estilo=txt_estilo.getText().toUpperCase().trim();
            if(!codigo_estilo.equalsIgnoreCase("")){
                if(!Validacion.repite_codigo_estilo(codigo_estilo)){
                    String version=txt_version.getText().toUpperCase().trim();
                    if(!version.equalsIgnoreCase("")){
                        String division=txt_division.getText().toUpperCase().trim();
                        if(!division.equalsIgnoreCase("")){
                            String descripcion=txt_descripcion.getText().toUpperCase().trim();
                            if(!descripcion.equalsIgnoreCase("")){
                                String destino=txt_destino.getText().toUpperCase().trim();
                                if(!destino.equalsIgnoreCase("")){
                                    if(!Validacion.existencia_numero(destino)){
                                        String temporada=txt_temporada.getText().toUpperCase().trim();
                                        if(!temporada.equalsIgnoreCase("")){
                                            String tela_principal=txt_telaPrincipal.getText().toUpperCase().trim();
                                            if(!tela_principal.equalsIgnoreCase("")){
                                                String proceso=txt_proceso.getText().toUpperCase().trim();
                                                if(!proceso.equalsIgnoreCase("")){
                                                    if(!Validacion.existencia_numero(proceso)){
                                                        String artes=txt_arte.getText().toUpperCase().trim();
                                                        if(!artes.equalsIgnoreCase("")){
                                                            if(!Validacion.existencia_numero(artes)){
                                                                String etiqueta=txt_etiqueta.getText().toUpperCase().trim();
                                                                if(!etiqueta.equalsIgnoreCase("")){
                                                                    if(!Validacion.existencia_numero(etiqueta)){
                                                                        String fechaString="";
                                                                        Date fecha=txt_fechaCreacion.getDate();
                                                                        if(fecha!=null){
                                                                            int input=JOptionPane.showConfirmDialog(null, "Estás seguro?","Escoger una opción",2,3);
                                                                            if(input==0){
                                                                                SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yy");
                                                                                fechaString=sdf.format(fecha);

                                                                                cn=Conection.getConnection();
                                                                                st=cn.createStatement();

                                                                                st.executeUpdate("insert into dbo.FICHA_TECNICA(COD_ESTILO,VERSION,DIVISION,DESCRIPCION,DESTINO,TEMPORADA,TELA_PRICNIPAL,PROCESO,ARTES,ETIQUETA,FECHA_CREACION) VALUES('"+codigo_estilo+"','"+version+"','"+division+"','"+descripcion+"','"+destino+"','"+temporada+"','"+tela_principal+"','"+proceso+"','"+artes+"','"+etiqueta+"',convert(datetime,'"+fechaString+"',5))");

                                                                                JOptionPane.showMessageDialog(null, "Se ingresó correctamente!!");     
                                                                            }
                                                                        }else{
                                                                            JOptionPane.showMessageDialog(null,"Complete todos los campos!!","Mensaje",3);
                                                                        }
                                                                    }else{
                                                                        JOptionPane.showMessageDialog(null,"La etiqueta no debe contener números!!","Mensaje",2);
                                                                    }
                                                                }else{
                                                                    JOptionPane.showMessageDialog(null,"Complete todos los campos!!","Mensaje",3);
                                                                }
                                                            }else{
                                                                JOptionPane.showMessageDialog(null,"Artes no debe contener números!!","Mensaje",2);
                                                            }
                                                        }else{
                                                            JOptionPane.showMessageDialog(null,"Complete todos los campos!!","Mensaje",3);
                                                        }
                                                    }else{
                                                        JOptionPane.showMessageDialog(null,"El proceso no debe contener números!!","Mensaje",2);
                                                    }
                                                }else{
                                                    JOptionPane.showMessageDialog(null,"Complete todos los campos!!","Mensaje",3);
                                                }
                                            }else{
                                                JOptionPane.showMessageDialog(null,"Complete todos los campos!!","Mensaje",3);
                                            }
                                        }else{
                                           JOptionPane.showMessageDialog(null,"Complete todos los campos!!","Mensaje",3); 
                                        }
                                    }else{
                                        JOptionPane.showMessageDialog(null,"El destino no debe contener números!!","Mensaje",2);
                                    }
                                }else{
                                    JOptionPane.showMessageDialog(null,"Complete todos los campos!!","Mensaje",3);
                                }
                            }else{
                                JOptionPane.showMessageDialog(null,"Complete todos los campos!!","Mensaje",3);
                            }
                        }else{
                            JOptionPane.showMessageDialog(null,"Complete todos los campos!!","Mensaje",3);
                        }
                    }else{
                        JOptionPane.showMessageDialog(null,"Complete todos los campos!!","Mensaje",3);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Ese codigo de estilo no existe!!","Mensaje",2);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Complete todos los campos!!","Mensaje",3);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        txt_estilo.setText("");
        txt_version.setText("");
        txt_division.setText("");
        txt_descripcion.setText("");
        txt_destino.setText("");
        txt_temporada.setText("");
        txt_telaPrincipal.setText("");
        txt_proceso.setText("");
        txt_arte.setText("");
        txt_etiqueta.setText("");
        txt_fechaCreacion.setDate(null);
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Frm8 obj=new Frm8();
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        obj.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField txt_arte;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_destino;
    private javax.swing.JTextField txt_division;
    private javax.swing.JTextField txt_estilo;
    private javax.swing.JTextField txt_etiqueta;
    private com.toedter.calendar.JDateChooser txt_fechaCreacion;
    private javax.swing.JTextField txt_proceso;
    private javax.swing.JTextField txt_telaPrincipal;
    private javax.swing.JTextField txt_temporada;
    private javax.swing.JTextField txt_version;
    // End of variables declaration//GEN-END:variables
}
