/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import conn.Conection;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rolando Andre
 */
public class Frm9 extends javax.swing.JFrame {

    /**
     * Creates new form Frm9
     */
    DefaultTableModel modelo=new DefaultTableModel();
    
    private String codigo_estilo;
    private String codigo_estilo2;
    private String nombre_empleado;
    private String fecha_inicio;
    private boolean selecionado=false;
    private boolean select_table=false;
    
    public Frm9() {
        initComponents();
        tabla.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_codigoEstilo = new javax.swing.JTextField();
        btn_cargarEmpleados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spin1 = new javax.swing.JSpinner();
        spin2 = new javax.swing.JSpinner();
        btn_modificar = new javax.swing.JButton();
        cbo_empleado = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1030, 400));
        setPreferredSize(new java.awt.Dimension(1038, 545));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1047, 500));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo de estilo:");

        btn_cargarEmpleados.setForeground(new java.awt.Color(102, 102, 102));
        btn_cargarEmpleados.setText("Cargar Empleados");
        btn_cargarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarEmpleadosActionPerformed(evt);
            }
        });

        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Prendas bien elaboradas:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Prendas mal elaboradas:");

        spin1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        spin2.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        btn_modificar.setForeground(new java.awt.Color(102, 102, 102));
        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        cbo_empleado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...................................................." }));
        cbo_empleado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_empleadoItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MANTENER ESTÁNDARES DE PRODUCCIÓN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(btn_cargarEmpleados)
                        .addGap(21, 21, 21)
                        .addComponent(cbo_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(360, 360, 360)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(420, 420, 420)
                                .addComponent(jLabel1)
                                .addGap(20, 20, 20)
                                .addComponent(txt_codigoEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(20, 20, 20)
                                .addComponent(spin1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(22, 22, 22)
                                .addComponent(spin2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(spin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_codigoEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_modificar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_cargarEmpleados)
                            .addComponent(cbo_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jMenu1.setText("Opción");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Regresar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cargarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarEmpleadosActionPerformed
        Connection cn=null;
        Statement st=null;
        try{
            selecionado=false;
            String codigo_estilo=txt_codigoEstilo.getText().toUpperCase().trim();
            if(!codigo_estilo.equalsIgnoreCase("")){
                if(Validacion.existe_codigo_estilo(codigo_estilo)){
                    cn=Conection.getConnection();
                    st=cn.createStatement();
                    cbo_empleado.removeAllItems();
                    boolean cantidad=false;
                    
                    ResultSet rs=st.executeQuery("SELECT E.APELLIDO+', '+E.NOMBRE FROM DBO.EMPLEADO E,DBO.EMPLEADO_FICHA EF,DBO.FICHA_TECNICA FT WHERE E.COD_EMP=EF.COD_EMP AND FT.COD_FICHA=EF.COD_FICHA AND FT.COD_ESTILO='"+codigo_estilo+"'");
                    
                    
                    cbo_empleado.addItem("....................................................");
                    while(rs.next()){
                        cbo_empleado.addItem(rs.getString(1));
                        cantidad=true;
                    }
                    
                    if(cantidad){
                        this.codigo_estilo=codigo_estilo;
                        selecionado=true;
                        modelo.setColumnCount(0);
                        modelo.setRowCount(0);
                        JOptionPane.showMessageDialog(null,"Se cargó correctamente!!");
                    }else{
                        JOptionPane.showMessageDialog(null,"No existen empleados asignados a esta ficha ténica!!");
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null,"Codigo de estilo no existe!!","Mensaje",3);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Complete el campo!!","Mensaje",3);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btn_cargarEmpleadosActionPerformed

    private void cbo_empleadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_empleadoItemStateChanged
        if(selecionado){
            if(evt.getSource() == cbo_empleado){
                try{
                    String nombre_empleado=cbo_empleado.getSelectedItem().toString().trim();
                    if(!nombre_empleado.equalsIgnoreCase("....................................................")){
                        cargarTabla(nombre_empleado,this.codigo_estilo);
                    }else{
                         JOptionPane.showMessageDialog(null,"Seleccione un empleado valido!!","Mensaje",3);
                    }
                }catch(Exception ex){
                     JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_cbo_empleadoItemStateChanged

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        Connection cn=null;
        Statement st=null;
        try{
            cn=Conection.getConnection();
            st=cn.createStatement();
            
            if(select_table){
                
                int codigo_ficha=0,codigo_empleado=0,prendas_bien=0,prendas_mal=0;
            
                ResultSet rs1=st.executeQuery("SELECT FT.COD_FICHA FROM DBO.FICHA_TECNICA FT WHERE FT.COD_ESTILO='"+this.codigo_estilo2+"'");

                if(rs1.next()){
                    codigo_ficha=rs1.getInt(1);
                }

                ResultSet rs2=st.executeQuery("SELECT E.COD_EMP FROM DBO.EMPLEADO E WHERE E.APELLIDO+', '+E.NOMBRE='"+this.nombre_empleado+"'");

                if(rs2.next()){
                    codigo_empleado=rs2.getInt(1);
                }
                
                prendas_bien=(int)spin1.getValue();
                prendas_mal=(int)spin2.getValue();
                
                st.executeUpdate("UPDATE DBO.AVANCE SET PRENDAS_BIEN='"+Integer.toString(prendas_bien)+"',PRENDAS_MAL='"+Integer.toString(prendas_mal)+"' WHERE CONVERT(VARCHAR,FECHA_INICIO,105)=CONVERT(VARCHAR,'"+this.fecha_inicio+"',105)");
                
                cargarTabla(this.nombre_empleado, this.codigo_estilo2);
                this.fecha_inicio=null;
                this.codigo_estilo2=null;
                this.nombre_empleado=null;
                
                JOptionPane.showMessageDialog(null,"se modificó correctamente!!");
            }else{
                JOptionPane.showMessageDialog(null,"seleccione una fila de la tabla!!");
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        int numero_fila=tabla.getSelectedRow();
        if(numero_fila>=0){
            select_table=true;
            this.codigo_estilo2=tabla.getValueAt(numero_fila, 0).toString().toUpperCase().trim();
            this.nombre_empleado=tabla.getValueAt(numero_fila, 1).toString().toUpperCase().trim();
            spin1.setValue(Integer.parseInt(tabla.getValueAt(numero_fila, 2).toString()));
            spin2.setValue(Integer.parseInt(tabla.getValueAt(numero_fila, 3).toString()));
            this.fecha_inicio=tabla.getValueAt(numero_fila, 4).toString().toUpperCase().trim();
        }
    }//GEN-LAST:event_tablaMouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Frm3 obj=new Frm3();
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        obj.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    private void cargarTabla(String nombre_empleado,String codigo_estilo){
        Connection cn=null;
        Statement st=null;
        try{
            select_table=false;
                    
            cn=Conection.getConnection();
            st=cn.createStatement();
            
            int codigo_ficha=0,codigo_empleado=0;
            
            ResultSet rs2=st.executeQuery("SELECT FT.COD_FICHA FROM DBO.FICHA_TECNICA FT WHERE FT.COD_ESTILO='"+codigo_estilo+"'");
            
            if(rs2.next()){
                codigo_ficha=rs2.getInt(1);
            }
            
            ResultSet rs3=st.executeQuery("SELECT E.COD_EMP FROM DBO.EMPLEADO E WHERE E.APELLIDO+', '+E.NOMBRE='"+nombre_empleado+"'");
            
            if(rs3.next()){
                codigo_empleado=rs3.getInt(1);
            }
            
            ResultSet rs=st.executeQuery("SELECT FT.COD_ESTILO AS \"CODIGO DE ESTILO\",E.APELLIDO+', '+E.NOMBRE AS \"EMPLEADO\",A.PRENDAS_BIEN AS \"PRENDAS BIEN ELABORADAS\",A.PRENDAS_MAL AS \"PRENDAS MAL ELABORADAS\",CONVERT(VARCHAR,A.FECHA_INICIO,105) AS \"FECHA DE AVANCE\" FROM DBO.EMPLEADO E,DBO.AVANCE A,DBO.FICHA_TECNICA FT WHERE E.COD_EMP=A.COD_EMP AND FT.COD_FICHA=A.COD_FICHA AND FT.COD_FICHA='"+Integer.toString(codigo_ficha)+"' AND E.COD_EMP='"+Integer.toString(codigo_empleado)+"'");
            
            modelo.setColumnCount(0);
            modelo.setRowCount(0);
            
            ResultSetMetaData md=rs.getMetaData();
            int num_column=md.getColumnCount();
            
            for(int i=1;i<=num_column;i++){
                modelo.addColumn(md.getColumnLabel(i));
            }
            
            while(rs.next()){
                Object[] fila=new Object[num_column];
                for(int i=0;i<num_column;i++){
                    fila[i]=rs.getObject(i+1);
                }
                modelo.addRow(fila);
            }
                    
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cargarEmpleados;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JComboBox cbo_empleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spin1;
    private javax.swing.JSpinner spin2;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txt_codigoEstilo;
    // End of variables declaration//GEN-END:variables
}
